#!/usr/bin/env zsh
if [ -d "$HOME/.oh-my-zsh" ]; then
    ZSH="$HOME/.oh-my-zsh"
else
    ZSH=$(grep -E '^\s*export\s+ZSH=' "${HOME}/.zshrc" 2>/dev/null | head -1 | gsed -r 's/^\s*export\s+ZSH=//g' 2>/dev/null)
    ZSH=$(eval echo "$ZSH" 2>/dev/null)
fi

[ -x "$ZSH/tools/upgrade.sh" ]  && "$ZSH/tools/upgrade.sh" -i -v default

ZSH_CUSTOM="$ZSH/custom"

wd=`pwd`

if [ -d "${ZSH_CUSTOM}/themes/powerlevel10k" ]; then
    cd "${ZSH_CUSTOM}/themes/powerlevel10k"
    git pull 2&>/dev/null
fi

while IFS= read -r dirp; do
    cd "$dirp"
    git pull 2&>/dev/null
done < <(find ${ZSH_CUSTOM}/plugins/ -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | grep -Ev '/example$' 2>/dev/null)

for dirp in "$HOME/opt/open-webui/open-webui"; do
    cd "$dirp"
    git pull 2&>/dev/null
done
cd "$wd"

